name: Git Commit Info

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  declare_variables:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ,windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract Commit Info
      id: extract_commit_info
      uses: zxc30314/git-commit-info-action@v1
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Show Commit Information
      run: |
          echo "Commit SHA: ${{ steps.extract_commit_info.outputs.sha }}"
          echo "Commit Short SHA: ${{ steps.extract_commit_info.outputs.sha_short }}"
          echo "Commit URL: ${{ steps.extract_commit_info.outputs.url }}"
          echo "Commit Author: ${{ steps.extract_commit_info.outputs.username }}"
          echo "Commit Message: ${{ steps.extract_commit_info.outputs.commit_message }}"   
